# fly.toml app configuration file generated for nupo-rag-server
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "nupo-rag-server"
primary_region = "ams"  # Amsterdam - close to Denmark

[build]

[deploy]
  release_command = "python -c 'import sys; print(\"Release command completed\")'"

[env]
  PORT = "8000"
  HOST = "0.0.0.0"
  PYTHONUNBUFFERED = "1"
  PYTHONDONTWRITEBYTECODE = "1"
  # Keep server active
  FLY_KEEP_ALIVE = "1"

[experimental]
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "1s"
    method = "get"
    path = "/api/status"
    protocol = "http"
    tls_skip_verify = false

    [services.http_checks.headers]
      Content-Type = "application/json"

[[mounts]]
  source = "nupo_rag_storage"
  destination = "/app/persistent"
  initial_size = "10gb"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false  # Keep machines running
  auto_start_machines = true
  min_machines_running = 1    # Always keep 1 machine running
  max_machines_running = 3    # Scale up to 3 if needed

[http_service.concurrency]
  type = "requests"
  hard_limit = 200
  soft_limit = 150

# VM Configuration
[vm]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048

# Keep app alive configuration
[[services.script_checks]]
  interval = "1m"
  timeout = "5s"
  script = "curl -f http://localhost:8000/api/status"
